/*
用途：
1. 查询5组MES任务SQL涉及的Oracle对象、字段类型及声明最大长度。
2. 查询字符字段当前数据的实际最大字符数和最大字节数。

执行账号：FWMES
说明：
- DATA_LENGTH：Oracle声明的最大字节数。
- CHAR_LENGTH：字符类型声明的最大字符数。
- CHAR_USED：B表示按字节定义，C表示按字符定义。
- 实际最大长度只反映执行查询时已有数据，不代表数据库字段允许的上限。
*/

/* 一、确认当前数据库用户和会话时区 */
SELECT USER AS CURRENT_USER,
       SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SESSIONTIMEZONE AS SESSION_TIMEZONE,
       DBTIMEZONE AS DATABASE_TIMEZONE
FROM DUAL;

/* 二、查询相关字段的Oracle类型和声明最大长度 */
WITH REQUIRED_COLUMNS AS (
    SELECT 1 AS OBJECT_ORDER, 'V_FW_WIP_SUBLOT' AS OBJECT_NAME, 1 AS COLUMN_ORDER, 'LOT' AS COLUMN_NAME FROM DUAL
    UNION ALL SELECT 1, 'V_FW_WIP_SUBLOT', 2, 'WORKORDER' FROM DUAL
    UNION ALL SELECT 1, 'V_FW_WIP_SUBLOT', 3, 'STEP' FROM DUAL
    UNION ALL SELECT 1, 'V_FW_WIP_SUBLOT', 4, 'STATE' FROM DUAL
    UNION ALL SELECT 1, 'V_FW_WIP_SUBLOT', 5, 'TASK' FROM DUAL
    UNION ALL SELECT 1, 'V_FW_WIP_SUBLOT', 6, 'EQP' FROM DUAL
    UNION ALL SELECT 1, 'V_FW_WIP_SUBLOT', 7, 'LASTTIME' FROM DUAL

    UNION ALL SELECT 2, 'FW_WIP_TRANS', 1, 'LOT' FROM DUAL
    UNION ALL SELECT 2, 'FW_WIP_TRANS', 2, 'DATES' FROM DUAL
    UNION ALL SELECT 2, 'FW_WIP_TRANS', 3, 'TASK' FROM DUAL
    UNION ALL SELECT 2, 'FW_WIP_TRANS', 4, 'EQP' FROM DUAL

    UNION ALL SELECT 3, 'FW_EQPRES_EQPINFORMATION', 1, 'EQPNO' FROM DUAL
    UNION ALL SELECT 3, 'FW_EQPRES_EQPINFORMATION', 2, 'AREA' FROM DUAL
    UNION ALL SELECT 3, 'FW_EQPRES_EQPINFORMATION', 3, 'STEP' FROM DUAL
)
SELECT C.OWNER,
       C.TABLE_NAME AS OBJECT_NAME,
       C.COLUMN_ID,
       C.COLUMN_NAME,
       C.DATA_TYPE,
       CASE
           WHEN C.DATA_TYPE IN ('CHAR', 'VARCHAR2', 'NCHAR', 'NVARCHAR2') THEN
               C.DATA_TYPE || '(' || C.CHAR_LENGTH ||
               CASE C.CHAR_USED WHEN 'C' THEN ' CHAR' WHEN 'B' THEN ' BYTE' END || ')'
           WHEN C.DATA_TYPE = 'NUMBER' AND C.DATA_PRECISION IS NOT NULL THEN
               'NUMBER(' || C.DATA_PRECISION ||
               CASE WHEN C.DATA_SCALE IS NOT NULL THEN ',' || C.DATA_SCALE END || ')'
           WHEN C.DATA_TYPE LIKE 'TIMESTAMP%' AND C.DATA_SCALE IS NOT NULL THEN
               C.DATA_TYPE || '(' || C.DATA_SCALE || ')'
           ELSE C.DATA_TYPE
       END AS FULL_DATA_TYPE,
       C.DATA_LENGTH AS DECLARED_MAX_BYTES,
       C.CHAR_LENGTH AS DECLARED_MAX_CHARS,
       C.CHAR_USED,
       C.DATA_PRECISION,
       C.DATA_SCALE,
       C.NULLABLE,
       C.DATA_DEFAULT
FROM ALL_TAB_COLUMNS C
JOIN REQUIRED_COLUMNS R
  ON R.OBJECT_NAME = C.TABLE_NAME
 AND R.COLUMN_NAME = C.COLUMN_NAME
WHERE C.OWNER = UPPER(SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA'))
ORDER BY R.OBJECT_ORDER, R.COLUMN_ORDER;

/* 三、检查是否存在未查到的对象或字段；正常结果应为0行 */
WITH REQUIRED_COLUMNS AS (
    SELECT 'V_FW_WIP_SUBLOT' AS OBJECT_NAME, 'LOT' AS COLUMN_NAME FROM DUAL
    UNION ALL SELECT 'V_FW_WIP_SUBLOT', 'WORKORDER' FROM DUAL
    UNION ALL SELECT 'V_FW_WIP_SUBLOT', 'STEP' FROM DUAL
    UNION ALL SELECT 'V_FW_WIP_SUBLOT', 'STATE' FROM DUAL
    UNION ALL SELECT 'V_FW_WIP_SUBLOT', 'TASK' FROM DUAL
    UNION ALL SELECT 'V_FW_WIP_SUBLOT', 'EQP' FROM DUAL
    UNION ALL SELECT 'V_FW_WIP_SUBLOT', 'LASTTIME' FROM DUAL
    UNION ALL SELECT 'FW_WIP_TRANS', 'LOT' FROM DUAL
    UNION ALL SELECT 'FW_WIP_TRANS', 'DATES' FROM DUAL
    UNION ALL SELECT 'FW_WIP_TRANS', 'TASK' FROM DUAL
    UNION ALL SELECT 'FW_WIP_TRANS', 'EQP' FROM DUAL
    UNION ALL SELECT 'FW_EQPRES_EQPINFORMATION', 'EQPNO' FROM DUAL
    UNION ALL SELECT 'FW_EQPRES_EQPINFORMATION', 'AREA' FROM DUAL
    UNION ALL SELECT 'FW_EQPRES_EQPINFORMATION', 'STEP' FROM DUAL
)
SELECT R.OBJECT_NAME,
       R.COLUMN_NAME,
       '对象或字段未在当前Schema中找到' AS ERROR_MESSAGE
FROM REQUIRED_COLUMNS R
LEFT JOIN ALL_TAB_COLUMNS C
  ON C.OWNER = UPPER(SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA'))
 AND C.TABLE_NAME = R.OBJECT_NAME
 AND C.COLUMN_NAME = R.COLUMN_NAME
WHERE C.COLUMN_NAME IS NULL
ORDER BY R.OBJECT_NAME, R.COLUMN_NAME;

/*
四、查询字符字段当前数据的实际最大长度
警告：本节会扫描相关视图和表，数据量较大时可能对MES数据库造成压力。
请优先执行前3节；本节仅在客户IT确认后，于非生产高峰期单独执行。
*/
SELECT 'V_FW_WIP_SUBLOT' AS OBJECT_NAME,
       'LOT' AS COLUMN_NAME,
       MAX(LENGTH(LOT)) AS ACTUAL_MAX_CHARS,
       MAX(LENGTHB(LOT)) AS ACTUAL_MAX_BYTES
FROM V_FW_WIP_SUBLOT
UNION ALL
SELECT 'V_FW_WIP_SUBLOT', 'WORKORDER', MAX(LENGTH(WORKORDER)), MAX(LENGTHB(WORKORDER))
FROM V_FW_WIP_SUBLOT
UNION ALL
SELECT 'V_FW_WIP_SUBLOT', 'STEP', MAX(LENGTH(STEP)), MAX(LENGTHB(STEP))
FROM V_FW_WIP_SUBLOT
UNION ALL
SELECT 'V_FW_WIP_SUBLOT', 'STATE', MAX(LENGTH(STATE)), MAX(LENGTHB(STATE))
FROM V_FW_WIP_SUBLOT
UNION ALL
SELECT 'V_FW_WIP_SUBLOT', 'TASK', MAX(LENGTH(TASK)), MAX(LENGTHB(TASK))
FROM V_FW_WIP_SUBLOT
UNION ALL
SELECT 'V_FW_WIP_SUBLOT', 'EQP', MAX(LENGTH(EQP)), MAX(LENGTHB(EQP))
FROM V_FW_WIP_SUBLOT

UNION ALL
SELECT 'FW_WIP_TRANS', 'LOT', MAX(LENGTH(LOT)), MAX(LENGTHB(LOT))
FROM FW_WIP_TRANS
UNION ALL
SELECT 'FW_WIP_TRANS', 'TASK', MAX(LENGTH(TASK)), MAX(LENGTHB(TASK))
FROM FW_WIP_TRANS
UNION ALL
SELECT 'FW_WIP_TRANS', 'EQP', MAX(LENGTH(EQP)), MAX(LENGTHB(EQP))
FROM FW_WIP_TRANS

UNION ALL
SELECT 'FW_EQPRES_EQPINFORMATION', 'EQPNO', MAX(LENGTH(EQPNO)), MAX(LENGTHB(EQPNO))
FROM FW_EQPRES_EQPINFORMATION
UNION ALL
SELECT 'FW_EQPRES_EQPINFORMATION', 'AREA', MAX(LENGTH(AREA)), MAX(LENGTHB(AREA))
FROM FW_EQPRES_EQPINFORMATION
UNION ALL
SELECT 'FW_EQPRES_EQPINFORMATION', 'STEP', MAX(LENGTH(STEP)), MAX(LENGTHB(STEP))
FROM FW_EQPRES_EQPINFORMATION
ORDER BY OBJECT_NAME, COLUMN_NAME;
